[build]
  base      = "consumer-app"
  command   = "npm install && npm run build"
  publish   = "public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY      = "true"

[functions]
  node_bundler   = "zisi"
  included_files = ["views/**", "data/**", "helpers/**", "middleware/**", "routes/**"]

[[redirects]]
  from   = "/css/*"
  to     = "/css/:splat"
  status = 200

[[redirects]]
  from   = "/*"
  to     = "/.netlify/functions/server"
  status = 200
